exports.Key = {
    Home: 'home',
    Order: 'order',
    Product: 'product',
    Inventory: 'inventory',
    Collection: 'collection',
    Banner: 'banner',
    Customer: 'customer',
    Analysis: 'analysis',
    Marketing: 'marketing',
    Discount: 'discount',
    OnlineStore: 'onlinestore',
    BlogPost: 'blogpost',
    Page: 'page',
    Navigation: 'navigation',
    Preferences: 'preference',
    Theme: 'theme',
    Domain: 'domain',
    Setting: 'setting',
}
